---
# This role will install flannel on all invokers

- name: add flannel vars
  set_fact:
    flannel_env_vars:
      FLANNELD_PUBLIC_IP: "{{ ansible_host }}"
      FLANNELD_ETCD_PREFIX: "{{ flannel.etcd.prefix }}"
      FLANNELD_ETCD_ENDPOINTS: "http://{{ hostvars[groups['etcds'][0]]['ansible_host'] }}:{{ etcd.advertisedPort }}"

- name: "(re)start flannel using '{{ flannel_image }}'"
  vars:
    flannel_image: "{{ flannel.docker_image | default('quay.io/coreos/flannel:' ~ flannel.version) }}"
  docker_container:
    name: flannel{{ groups['invokers'].index(inventory_hostname) }}
    image: "{{ flannel_image }}"
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    env: "{{ flannel_env_vars }}"
    network_mode: host
    privileged: true
    volumes:
      - "{{ flannel.subnetDir }}:/run/flannel:rw"
  retries: "{{ docker.pull.retries }}"
  delay: "{{ docker.pull.delay }}"


# We have to use the v2 API, but Ansible only supports v3 at the moment. Data stored in one isn't accessible
# to the other. 
# - name: store flannel configuration in etcd
#   uri:
#     url: "http://{{ hostvars[groups['etcds'][0]]['ansible_host'] }}:{{ etcd.advertisedPort }}/v2/keys{{ flannel.etcd.prefix }}/config"
#     method: PUT
#     follow_redirects: all
#     body: "{{ { 'value': flannel.config } | to_json }}"